# Generated by Django 4.0.4 on 2022-04-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='fee_charged',
        ),
        migrations.AddField(
            model_name='subscription',
            name='card_add_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='card_token',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
