# Generated by Django 4.0.4 on 2022-05-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_remove_subscription_fee_charged_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='card_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_client_secret',
            field=models.CharField(default=str, max_length=256),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='card_token',
            field=models.TextField(default=str),
        ),
    ]
