# Generated by Django 4.0.4 on 2022-05-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_subscription_card_valid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='card_token',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='stripe_client_secret',
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_method_id',
            field=models.CharField(default=str, max_length=256),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_customer_id',
            field=models.CharField(default=str, max_length=256),
        ),
    ]
