# Generated by Django 4.0.4 on 2022-05-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_remove_subscription_card_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, default=str, max_length=256),
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscription_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
